# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: "AI Builders: LatinX Edition"
email: "info@aibuilderslatinx.com"
description: "AI Builders: LatinX Edition is a podcast about technology, innovation, and the LatinX community. Each episode explores the impact of AI and technology on our world, featuring voices and stories from the LatinX community."
subtitle: "Technology | Innovation | Community"
lang: "en-us"
author: "Victor Ramirez"
copyright: "© 2025"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aibuilderslatinx.com" # the base hostname & protocol for your site
twitter_username: "aibuilderslatinx"
github_username: "aibuilderslatinx"

permalink: /:year/:title.html

#Timezone
timezone: America/Los_Angeles

#Setup for Pages
## include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']